FROM ubuntu as build

RUN apt-get update && apt-get install -y \
  autoconf \
  automake \
  build-essential \
  cmake \
  curl \
  g++ \
  git \
  libtool \
  make \
  pkg-config \
  unzip \
  && apt-get clean

ENV GRPC_RELEASE_TAG v1.16.0
ENV CALCULATOR_BUILD_PATH /usr/local/calculator

RUN git clone -b ${GRPC_RELEASE_TAG} https://github.com/grpc/grpc /var/local/git/grpc && \
    cd /var/local/git/grpc && \
    git submodule update --init --recursive

RUN echo "-- installing protobuf" && \
    cd /var/local/git/grpc/third_party/protobuf && \
    ./autogen.sh && ./configure --enable-shared && \
    make -j$(nproc) && make -j$(nproc) check && make install && make clean && ldconfig

RUN echo "-- installing grpc" && \
    cd /var/local/git/grpc && \
    make -j$(nproc) && make install && make clean && ldconfig \

RUN mkdir -p /opt/LogStorage
WORKDIR "/opt/LogStorage"
RUN git clone --single-branch --branch add_docker https://github.com/RahulKushwaha/replicated_counter.git
RUN mkdir -p /opt/LogStorage/replicated_counter/build
WORKDIR "/opt/LogStorage/replicated_counter/build"
RUN cmake ..