// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MetadataConfig.proto

#include "MetadataConfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace rk {
namespace project {
namespace counter {
PROTOBUF_CONSTEXPR MetadataConfig::MetadataConfig(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.versionid_)*/int64_t{0}
  , /*decltype(_impl_.previousversionid_)*/int64_t{0}
  , /*decltype(_impl_.startindex_)*/int64_t{0}
  , /*decltype(_impl_.endindex_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MetadataConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetadataConfigDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetadataConfigDefaultTypeInternal() {}
  union {
    MetadataConfig _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetadataConfigDefaultTypeInternal _MetadataConfig_default_instance_;
}  // namespace counter
}  // namespace project
}  // namespace rk
static ::_pb::Metadata file_level_metadata_MetadataConfig_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_MetadataConfig_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_MetadataConfig_2eproto = nullptr;

const uint32_t TableStruct_MetadataConfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::rk::project::counter::MetadataConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::rk::project::counter::MetadataConfig, _impl_.versionid_),
  PROTOBUF_FIELD_OFFSET(::rk::project::counter::MetadataConfig, _impl_.previousversionid_),
  PROTOBUF_FIELD_OFFSET(::rk::project::counter::MetadataConfig, _impl_.startindex_),
  PROTOBUF_FIELD_OFFSET(::rk::project::counter::MetadataConfig, _impl_.endindex_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::rk::project::counter::MetadataConfig)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::rk::project::counter::_MetadataConfig_default_instance_._instance,
};

const char descriptor_table_protodef_MetadataConfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024MetadataConfig.proto\022\022rk.project.count"
  "er\"d\n\016MetadataConfig\022\021\n\tversionId\030\001 \001(\003\022"
  "\031\n\021previousVersionId\030\002 \001(\003\022\022\n\nstartIndex"
  "\030\003 \001(\003\022\020\n\010endIndex\030\004 \001(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_MetadataConfig_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MetadataConfig_2eproto = {
    false, false, 152, descriptor_table_protodef_MetadataConfig_2eproto,
    "MetadataConfig.proto",
    &descriptor_table_MetadataConfig_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_MetadataConfig_2eproto::offsets,
    file_level_metadata_MetadataConfig_2eproto, file_level_enum_descriptors_MetadataConfig_2eproto,
    file_level_service_descriptors_MetadataConfig_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MetadataConfig_2eproto_getter() {
  return &descriptor_table_MetadataConfig_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MetadataConfig_2eproto(&descriptor_table_MetadataConfig_2eproto);
namespace rk {
namespace project {
namespace counter {

// ===================================================================

class MetadataConfig::_Internal {
 public:
};

MetadataConfig::MetadataConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:rk.project.counter.MetadataConfig)
}
MetadataConfig::MetadataConfig(const MetadataConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MetadataConfig* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.versionid_){}
    , decltype(_impl_.previousversionid_){}
    , decltype(_impl_.startindex_){}
    , decltype(_impl_.endindex_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.versionid_, &from._impl_.versionid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.endindex_) -
    reinterpret_cast<char*>(&_impl_.versionid_)) + sizeof(_impl_.endindex_));
  // @@protoc_insertion_point(copy_constructor:rk.project.counter.MetadataConfig)
}

inline void MetadataConfig::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.versionid_){int64_t{0}}
    , decltype(_impl_.previousversionid_){int64_t{0}}
    , decltype(_impl_.startindex_){int64_t{0}}
    , decltype(_impl_.endindex_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MetadataConfig::~MetadataConfig() {
  // @@protoc_insertion_point(destructor:rk.project.counter.MetadataConfig)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MetadataConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MetadataConfig::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MetadataConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:rk.project.counter.MetadataConfig)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.versionid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.endindex_) -
      reinterpret_cast<char*>(&_impl_.versionid_)) + sizeof(_impl_.endindex_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MetadataConfig::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 versionId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.versionid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 previousVersionId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.previousversionid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 startIndex = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.startindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 endIndex = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.endindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MetadataConfig::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rk.project.counter.MetadataConfig)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 versionId = 1;
  if (this->_internal_versionid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_versionid(), target);
  }

  // int64 previousVersionId = 2;
  if (this->_internal_previousversionid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_previousversionid(), target);
  }

  // int64 startIndex = 3;
  if (this->_internal_startindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_startindex(), target);
  }

  // int64 endIndex = 4;
  if (this->_internal_endindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_endindex(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rk.project.counter.MetadataConfig)
  return target;
}

size_t MetadataConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rk.project.counter.MetadataConfig)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 versionId = 1;
  if (this->_internal_versionid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_versionid());
  }

  // int64 previousVersionId = 2;
  if (this->_internal_previousversionid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_previousversionid());
  }

  // int64 startIndex = 3;
  if (this->_internal_startindex() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_startindex());
  }

  // int64 endIndex = 4;
  if (this->_internal_endindex() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_endindex());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MetadataConfig::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MetadataConfig::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MetadataConfig::GetClassData() const { return &_class_data_; }


void MetadataConfig::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MetadataConfig*>(&to_msg);
  auto& from = static_cast<const MetadataConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rk.project.counter.MetadataConfig)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_versionid() != 0) {
    _this->_internal_set_versionid(from._internal_versionid());
  }
  if (from._internal_previousversionid() != 0) {
    _this->_internal_set_previousversionid(from._internal_previousversionid());
  }
  if (from._internal_startindex() != 0) {
    _this->_internal_set_startindex(from._internal_startindex());
  }
  if (from._internal_endindex() != 0) {
    _this->_internal_set_endindex(from._internal_endindex());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MetadataConfig::CopyFrom(const MetadataConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rk.project.counter.MetadataConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MetadataConfig::IsInitialized() const {
  return true;
}

void MetadataConfig::InternalSwap(MetadataConfig* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MetadataConfig, _impl_.endindex_)
      + sizeof(MetadataConfig::_impl_.endindex_)
      - PROTOBUF_FIELD_OFFSET(MetadataConfig, _impl_.versionid_)>(
          reinterpret_cast<char*>(&_impl_.versionid_),
          reinterpret_cast<char*>(&other->_impl_.versionid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MetadataConfig::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MetadataConfig_2eproto_getter, &descriptor_table_MetadataConfig_2eproto_once,
      file_level_metadata_MetadataConfig_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace counter
}  // namespace project
}  // namespace rk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::rk::project::counter::MetadataConfig*
Arena::CreateMaybeMessage< ::rk::project::counter::MetadataConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::rk::project::counter::MetadataConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
