global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "counter_app_1"
    static_configs:
      - targets: ["localhost:10099"]
  - job_name: "counter_app_2"
    static_configs:
      - targets: ["localhost:20099"]
  - job_name: "counter_app_3"
    static_configs:
      - targets: ["localhost:30099"]
  - job_name: "counter_app_4"
    static_configs:
      - targets: ["localhost:40099"]
  - job_name: "counter_app_5"
    static_configs:
      - targets: ["localhost:50099"]