# proto-file: applications/mydb/backend/proto/db.proto
# proto-message: Table

name: "meta_db_table"
id: 1
db{
  name: "meta"
  id: 1
}

primary_key_index{
  id: 1
  name: "id_idx"
  column_ids: [1]
}

secondary_index[
  {
    id: 2
    name: "name_idx"
    column_ids: [2]
  }
]

columns[
  {
    id: 1
    name: "id"
    column_type: 0
  },
  {
    id: 2
    name: "name"
    column_type: 1
  },
  {
    id: 3
    name: "secondary_index"
    column_type: 1
  },
  {
    id: 4
    name: "created"
    column_type: 1
  },
  {
    id: 5
    name: "modified"
    column_type: 1
  }
]