// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MetadataConfig.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MetadataConfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MetadataConfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MetadataConfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MetadataConfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MetadataConfig_2eproto;
namespace rk {
namespace projects {
namespace durable_log {
class MetadataConfig;
struct MetadataConfigDefaultTypeInternal;
extern MetadataConfigDefaultTypeInternal _MetadataConfig_default_instance_;
}  // namespace durable_log
}  // namespace projects
}  // namespace rk
PROTOBUF_NAMESPACE_OPEN
template<> ::rk::projects::durable_log::MetadataConfig* Arena::CreateMaybeMessage<::rk::projects::durable_log::MetadataConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rk {
namespace projects {
namespace durable_log {

// ===================================================================

class MetadataConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rk.projects.durable_log.MetadataConfig) */ {
 public:
  inline MetadataConfig() : MetadataConfig(nullptr) {}
  ~MetadataConfig() override;
  explicit PROTOBUF_CONSTEXPR MetadataConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MetadataConfig(const MetadataConfig& from);
  MetadataConfig(MetadataConfig&& from) noexcept
    : MetadataConfig() {
    *this = ::std::move(from);
  }

  inline MetadataConfig& operator=(const MetadataConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetadataConfig& operator=(MetadataConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MetadataConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const MetadataConfig* internal_default_instance() {
    return reinterpret_cast<const MetadataConfig*>(
               &_MetadataConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MetadataConfig& a, MetadataConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(MetadataConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MetadataConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MetadataConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MetadataConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MetadataConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MetadataConfig& from) {
    MetadataConfig::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MetadataConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rk.projects.durable_log.MetadataConfig";
  }
  protected:
  explicit MetadataConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionIdFieldNumber = 1,
    kPreviousVersionIdFieldNumber = 2,
    kStartIndexFieldNumber = 3,
    kEndIndexFieldNumber = 4,
    kPreviousVersionEndIndexFieldNumber = 5,
  };
  // int64 versionId = 1;
  void clear_versionid();
  int64_t versionid() const;
  void set_versionid(int64_t value);
  private:
  int64_t _internal_versionid() const;
  void _internal_set_versionid(int64_t value);
  public:

  // int64 previousVersionId = 2;
  void clear_previousversionid();
  int64_t previousversionid() const;
  void set_previousversionid(int64_t value);
  private:
  int64_t _internal_previousversionid() const;
  void _internal_set_previousversionid(int64_t value);
  public:

  // int64 startIndex = 3;
  void clear_startindex();
  int64_t startindex() const;
  void set_startindex(int64_t value);
  private:
  int64_t _internal_startindex() const;
  void _internal_set_startindex(int64_t value);
  public:

  // int64 endIndex = 4;
  void clear_endindex();
  int64_t endindex() const;
  void set_endindex(int64_t value);
  private:
  int64_t _internal_endindex() const;
  void _internal_set_endindex(int64_t value);
  public:

  // int64 previousVersionEndIndex = 5;
  void clear_previousversionendindex();
  int64_t previousversionendindex() const;
  void set_previousversionendindex(int64_t value);
  private:
  int64_t _internal_previousversionendindex() const;
  void _internal_set_previousversionendindex(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:rk.projects.durable_log.MetadataConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t versionid_;
    int64_t previousversionid_;
    int64_t startindex_;
    int64_t endindex_;
    int64_t previousversionendindex_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MetadataConfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MetadataConfig

// int64 versionId = 1;
inline void MetadataConfig::clear_versionid() {
  _impl_.versionid_ = int64_t{0};
}
inline int64_t MetadataConfig::_internal_versionid() const {
  return _impl_.versionid_;
}
inline int64_t MetadataConfig::versionid() const {
  // @@protoc_insertion_point(field_get:rk.projects.durable_log.MetadataConfig.versionId)
  return _internal_versionid();
}
inline void MetadataConfig::_internal_set_versionid(int64_t value) {
  
  _impl_.versionid_ = value;
}
inline void MetadataConfig::set_versionid(int64_t value) {
  _internal_set_versionid(value);
  // @@protoc_insertion_point(field_set:rk.projects.durable_log.MetadataConfig.versionId)
}

// int64 previousVersionId = 2;
inline void MetadataConfig::clear_previousversionid() {
  _impl_.previousversionid_ = int64_t{0};
}
inline int64_t MetadataConfig::_internal_previousversionid() const {
  return _impl_.previousversionid_;
}
inline int64_t MetadataConfig::previousversionid() const {
  // @@protoc_insertion_point(field_get:rk.projects.durable_log.MetadataConfig.previousVersionId)
  return _internal_previousversionid();
}
inline void MetadataConfig::_internal_set_previousversionid(int64_t value) {
  
  _impl_.previousversionid_ = value;
}
inline void MetadataConfig::set_previousversionid(int64_t value) {
  _internal_set_previousversionid(value);
  // @@protoc_insertion_point(field_set:rk.projects.durable_log.MetadataConfig.previousVersionId)
}

// int64 startIndex = 3;
inline void MetadataConfig::clear_startindex() {
  _impl_.startindex_ = int64_t{0};
}
inline int64_t MetadataConfig::_internal_startindex() const {
  return _impl_.startindex_;
}
inline int64_t MetadataConfig::startindex() const {
  // @@protoc_insertion_point(field_get:rk.projects.durable_log.MetadataConfig.startIndex)
  return _internal_startindex();
}
inline void MetadataConfig::_internal_set_startindex(int64_t value) {
  
  _impl_.startindex_ = value;
}
inline void MetadataConfig::set_startindex(int64_t value) {
  _internal_set_startindex(value);
  // @@protoc_insertion_point(field_set:rk.projects.durable_log.MetadataConfig.startIndex)
}

// int64 endIndex = 4;
inline void MetadataConfig::clear_endindex() {
  _impl_.endindex_ = int64_t{0};
}
inline int64_t MetadataConfig::_internal_endindex() const {
  return _impl_.endindex_;
}
inline int64_t MetadataConfig::endindex() const {
  // @@protoc_insertion_point(field_get:rk.projects.durable_log.MetadataConfig.endIndex)
  return _internal_endindex();
}
inline void MetadataConfig::_internal_set_endindex(int64_t value) {
  
  _impl_.endindex_ = value;
}
inline void MetadataConfig::set_endindex(int64_t value) {
  _internal_set_endindex(value);
  // @@protoc_insertion_point(field_set:rk.projects.durable_log.MetadataConfig.endIndex)
}

// int64 previousVersionEndIndex = 5;
inline void MetadataConfig::clear_previousversionendindex() {
  _impl_.previousversionendindex_ = int64_t{0};
}
inline int64_t MetadataConfig::_internal_previousversionendindex() const {
  return _impl_.previousversionendindex_;
}
inline int64_t MetadataConfig::previousversionendindex() const {
  // @@protoc_insertion_point(field_get:rk.projects.durable_log.MetadataConfig.previousVersionEndIndex)
  return _internal_previousversionendindex();
}
inline void MetadataConfig::_internal_set_previousversionendindex(int64_t value) {
  
  _impl_.previousversionendindex_ = value;
}
inline void MetadataConfig::set_previousversionendindex(int64_t value) {
  _internal_set_previousversionendindex(value);
  // @@protoc_insertion_point(field_set:rk.projects.durable_log.MetadataConfig.previousVersionEndIndex)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace durable_log
}  // namespace projects
}  // namespace rk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MetadataConfig_2eproto
