# proto-file: log/server/proto/ServerConfig.proto
# proto-message: ServerConfig

id: ""

sequencer_config {
  id: "SEQUENCER_01"
  ip_address{
    host: "127.0.0.1"
    port: 20001
  }
  seed_seq_num: 1
}

replica_config{
  id: "REPLICA_01"
  ip_address{
    host: "127.0.0.1"
    port: 20002
  }
}

metadata_config{
  id: "METADATA_01"
  ip_address{
    host: "127.0.0.1"
    port: 60003
  }
  data_directory: "/tmp/data/METADATA_01/"
}

admin_server_config{
  ip_address{
    host: "127.0.0.1"
    port: 20004
  }
}

metric_server_config{
  ip_address{
    host: "127.0.0.1"
    port: 20099
  }
}

replica_set[
  {
    id: "REPLICA_00"
    ip_address {
      host: "127.0.0.1"
      port: 10002
    }
    data_directory: "/tmp/data/REPLICA_00/"
  },
  {
    id: "REPLICA_01"
    ip_address {
      host: "127.0.0.1"
      port: 20002
    }
    data_directory: "/tmp/data/REPLICA_01/"
  },
  {
    id: "REPLICA_02",
    ip_address {
      host: "127.0.0.1"
      port: 30002
    }
    data_directory: "/tmp/data/REPLICA_02/"
  },
  {
    id: "REPLICA_03",
    ip_address {
      host: "127.0.0.1"
      port: 40002
    }
    data_directory: "/tmp/data/REPLICA_03/"
  },
  {
    id: "REPLICA_04",
    ip_address {
      host: "127.0.0.1"
      port: 50002
    }
    data_directory: "/tmp/data/REPLICA_04/"
  }
]

remote_sequencer_set[
  {
    id: "SEQUENCER_00"
    ip_address{
      host: "127.0.0.1"
      port: 10001
    }
  },
  #  {
  #    id: "SEQUENCER_01"
  #    ip_address{
  #      host: "127.0.0.1"
  #      port: 20001
  #    }
  #  },
  {
    id: "SEQUENCER_02"
    ip_address{
      host: "127.0.0.1"
      port: 30001
    }
  },
  {
    id: "SEQUENCER_03"
    ip_address{
      host: "127.0.0.1"
      port: 40001
    }
  },
  {
    id: "SEQUENCER_04"
    ip_address{
      host: "127.0.0.1"
      port: 50001
    }
  }
]