# proto-file: applications/counter/server/proto/CounterService.proto
# proto-message: CounterAppConfig

name: "COUNTER_APP_2"
data_directory: "/tmp/COUNTER_APP_2/"
ip_address: {
  host: "127.0.0.1",
  port: 20098,
}
