set(
        SOURCE_FILES_LIST

        applications/mydb/backend/tests/TestUtils.h
        applications/counter/CounterAppServer.h
        applications/counter/CounterAppEnsembleNode.h
        applications/counter/CounterApp.cc
        applications/counter/CounterApp.h
        applications/counter/CounterHealthCheck.cc
        applications/counter/CounterHealthCheck.h
        applications/counter/CounterAppStateMachine.cc
        applications/counter/CounterAppStateMachine.h
        applications/counter/CounterApplicator.cc
        applications/counter/CounterApplicator.h
        applications/counter/client/CounterAppClient.cc
        applications/counter/client/CounterAppClient.h
        applications/counter/server/CounterAppServer.h
        log/client/MetadataStoreClient.cc
        log/client/MetadataStoreClient.h
        log/client/ReplicaClient.cc
        log/client/ReplicaClient.h
        log/client/SequencerClient.cc
        log/client/SequencerClient.h
        log/impl/Ensemble.h
        log/impl/EnsembleConfig.h
        log/impl/EnsembleNode.h
        log/impl/FailureDetectorImpl.cc
        log/impl/FailureDetectorImpl.h
        log/impl/InMemoryMetadataStore.cc
        log/impl/InMemoryMetadataStore.h
        log/impl/PersistentMetadataStore.h
        log/impl/NanoLogStoreImpl.cc
        log/impl/NanoLogStoreImpl.h
        log/impl/NullSequencer.h
        log/impl/RegistryImpl.cc
        log/impl/RegistryImpl.h
        log/impl/RemoteMetadataStore.h
        log/impl/RemoteReplica.h
        log/impl/RemoteSequencer.h
        log/impl/ReplicaImpl.cc
        log/impl/ReplicaImpl.h
        log/impl/SequencerImpl.cc
        log/impl/SequencerImpl.h
        log/impl/InMemoryNanoLog.cc
        log/impl/InMemoryNanoLog.h
        log/impl/RocksNanoLog.h
        log/impl/RocksNanoLog.cc
        log/impl/NanoLogFactory.h
        log/impl/VirtualLogFactory.cc
        log/impl/VirtualLogFactory.h
        log/impl/VirtualLogImpl.cc
        log/impl/VirtualLogImpl.h
        log/include/Common.h
        log/include/FailureDetector.h
        log/include/HealthCheck.h
        log/include/MetadataStore.h
        log/include/NanoLog.h
        log/include/NanoLogStore.h
        log/include/Registry.h
        log/include/Replica.h
        log/include/Sequencer.h
        log/include/VirtualLog.h
        log/server/AdminServer.cc
        log/server/AdminServer.h
        log/server/MetadataServer.cc
        log/server/MetadataServer.h
        log/server/ReplicaServer.cc
        log/server/ReplicaServer.h
        log/server/LogServer.h
        log/server/SequencerServer.cc
        log/server/SequencerServer.h
        log/utils/FutureUtils.h
        log/utils/GrpcServerFactory.h
        log/utils/OrderedCompletionQueue.h
        log/utils/UuidGenerator.h
        log/utils/FlatMapSequential.h

        metrics/MetricsRegistry.h

        persistence/KVStoreLite.h
        persistence/RocksKVStoreLite.h
        persistence/TransactionalRocksKVStoreLite.h
        persistence/RocksDbFactory.h
        wor/include/WriteOnceRegister.h
        wor/include/WriteOnceRegisterChain.h
        wor/WriteOnceRegisterChainImpl.h
        wor/WriteOnceRegisterChainAppender.h
        wor/inmemory/InMemoryWriteOnceRegister.h
        wor/inmemory/InMemoryWriteOnceRegisterChain.h

        wor/paxos/include/Registry.h
        wor/paxos/include/Acceptor.h
        wor/paxos/include/Proposer.h
        wor/paxos/RegistryImpl.h
        wor/paxos/LocalAcceptor.h
        wor/paxos/LocalAcceptor.cc
        wor/paxos/Common.h
        wor/paxos/Common.cc
        wor/paxos/PaxosWriteOnceRegister.h
        wor/WORFactory.h
        wor/WORFactory.cc
        wor/paxos/server/Acceptor.h
        wor/paxos/client/AcceptorClient.h
        wor/paxos/RemoteAcceptor.h

        statemachine/include/StateMachine.h
        statemachine/NullStateMachine.h
        statemachine/RocksStateMachine.h
        statemachine/ConflictDetector.h
        statemachine/RocksTxnApplicator.h
        statemachine/MetadataStoreStateMachine.h
        statemachine/MetadataStoreApplicator.h
        statemachine/LogTrimApplicator.h
        statemachine/LogTrimStateMachine.h
        statemachine/VirtualLogStateMachine.h
        statemachine/SinkStateMachine.h
        statemachine/Factory.h
        statemachine/Common.h
)


set(
        MY_DB_SOURCE_FILES_LIST

        applications/mydb/backend/Bootstrap.h
        applications/mydb/backend/Common.h
        applications/mydb/backend/Db.cc
        applications/mydb/backend/Db.h
        applications/mydb/backend/DbDefaults.cc
        applications/mydb/backend/DbDefaults.h
        applications/mydb/backend/Errors.h
        applications/mydb/backend/KeySerializer.cc
        applications/mydb/backend/KeySerializer.h
        applications/mydb/backend/QueryExecutor.cc
        applications/mydb/backend/QueryExecutor.h
        applications/mydb/backend/QueryOptions.h
        applications/mydb/backend/QueryParser.cc
        applications/mydb/backend/QueryParser.h
        applications/mydb/backend/QueryPlan.h
        applications/mydb/backend/QueryPlanner.cc
        applications/mydb/backend/QueryPlanner.h
        applications/mydb/backend/RequestTransformer.h
        applications/mydb/backend/RocksDbFactory.h
        applications/mydb/backend/RocksReaderWriter.cc
        applications/mydb/backend/RocksReaderWriter.h
        applications/mydb/backend/RowSerializer.h
        applications/mydb/backend/SchemaStore.h
        applications/mydb/backend/server/DbServer.cc
        applications/mydb/backend/server/DbServer.h
        applications/mydb/backend/TableRow.cc
        applications/mydb/backend/TableRow.h
        applications/mydb/format/FormatTable.h
        applications/mydb/backend/PartitionMap.h

        applications/mydb/experimental/WaitForGraph.h
        applications/mydb/experimental/WaitForGraph.cc
        applications/mydb/experimental/Dfs.h
        applications/mydb/experimental/Dfs.cc
        applications/mydb/experimental/Models.h

        applications/mydb/backend/transaction/TwoPhaseCommit.cc
        applications/mydb/backend/transaction/TwoPhaseCommit.h
        applications/mydb/backend/transaction/TxnCoordinator.cc
        applications/mydb/backend/transaction/TxnCoordinator.h
        applications/mydb/backend/transaction/TxnManager.cc
        applications/mydb/backend/transaction/TxnManager.h
        applications/mydb/backend/transaction/Models.h
)